include:
  - template: Docker.gitlab-ci.yml
  - template: Ansible.gitlab-ci.yml

stages:
  - build
  - push
  - deploy

variables:
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"

build-image:
  stage: build
  before_script:
    - echo "Login to Docker Local Repository..."
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin  $CI_REGISTRY
  script:
    - echo "Build springboot Docker image..."
    - docker build -t $DOCKER_IMAGE .
    - echo $DOCKER_IMAGE
  after_script:
    - echo "Script executed successfully."
    - docker logout
  tags:
    - build

push-image:
  stage: push
  before_script:
    - echo "Login to Docker Local Repository..."
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin  $CI_REGISTRY
  script:
    - echo "Push springboot Docker image..."
    - docker push $DOCKER_IMAGE
  after_script:
    - echo "Script executed successfully."
    - echo "Logout from Docker Local Repository'..."
    - docker logout
  tags:
    - build

deploy-image:
  stage: deploy
  script:
    - echo "Deploy springboot Docker image..."
    - ansible-playbook -i "app.fiipractic.lan," deploy.yml
  tags: 
    - build
