- name: Install Docker
  hosts: all
  become: yes

  vars_files:
    - group_vars/all.yml

  vars:
    banner: |
      This server is restricted to authorized users only. All activities on this system are logged.
      Unauthorized access will be fully investigated and reported to the appropriate law enforcement agencies.

  tasks:
    - name: Firewalld disable
      service:
        name: firewalld
        state: stopped
        enabled: no

    - name: SELinux disable
      ansible.posix.selinux:
        state: disabled

    - name: Set timezone
      community.general.timezone:
        name: "{{ timezone }}"

    - name: Prohibit root login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin prohibit-password"
        state: present
      notify: restart sshd

    - name: Install CA
      copy:
        src: "{{ root_ca_local_path }}"
        dest: "{{ root_ca_remote_path }}"
        owner: root
        group: root
        mode: '0644'

    - name: Trust
      command: update-ca-trust extract

    - name: Set SSH banner file
      copy:
        dest: /etc/issue.net
        content: "{{ banner }}"
        owner: root
        group: root
        mode: '0644'

    - name: Enable SSH banner
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Banner'
        line: 'Banner /etc/issue.net'
      notify:
        - restart sshd

    - name: Docker repo
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable
        baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: yes

    - name: Install Docker
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ docker_packages }}"

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted

- name: Install Gitlab
  hosts: gitlab
  become: yes

  tasks:
    - name: Install runner
      yum:
        name: gitlab-runner
        state: present

    - name: Install CE
      yum: 
        name: gitlab-ce
        state: present 
