---
- name: Install Docker
  hosts: all
  become: yes
  tasks:

    - name: Add Docker repository
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable
        baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: yes

    - name: Install Docker
      package:
        name: "{{ item }}"
        state: present
      with_items:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

